import { Circle,CircleMarker,MapContainer,Popup,TileLayer,useMap,ZoomControl } from 'react-leaflet';
import { Crosshair } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';

function Fit({points,active,userLocation}){const map=useMap();useEffect(()=>{if(userLocation){map.flyTo([userLocation.lat,userLocation.lng],11,{duration:.5});return}const item=points.find((x)=>x.id===active)||points[0];if(item?.lat&&item?.lng)map.flyTo([item.lat,item.lng],active?12:10,{duration:.5});},[points,active,userLocation,map]);return null}

export function ResultsMap({items,groups:summaryGroups,coverage,mapNotice,mapLoading,active,onActive,radiusKm,setRadiusKm,userLocation,onUserLocation}){
  const [locationError,setLocationError]=useState('');
  const located=items.filter((item)=>item.location?.lat&&item.location?.lng);
  const pageGroups=useMemo(()=>{const map=new Map();for(const item of located){const key=`${item.location.lat.toFixed(3)}:${item.location.lng.toFixed(3)}`;if(!map.has(key))map.set(key,{city:item.location.city,state:item.location.state,lat:item.location.lat,lng:item.location.lng,records:0,institutions:new Map(),items:[]});const group=map.get(key);group.records++;group.items.push(item);const institution=item.institution;if(!group.institutions.has(String(institution.id)))group.institutions.set(String(institution.id),{...institution,records:0});group.institutions.get(String(institution.id)).records++}return [...map.values()].map((group)=>({...group,institutions:[...group.institutions.values()]}))},[located]);
  const groups=summaryGroups?.length?summaryGroups:pageGroups;
  const points=groups.map((group)=>({id:group.items?.[0]?.id,lat:group.lat,lng:group.lng}));
  const selected=items.find((item)=>item.id===active)||items[0];const center=userLocation?[userLocation.lat,userLocation.lng]:points[0]?[points[0].lat,points[0].lng]:[-14.235,-51.925];const circleCenter=userLocation||points[0];
  function locate(){if(!navigator.geolocation){setLocationError('Seu navegador não oferece localização. Digite uma cidade na busca.');return}navigator.geolocation.getCurrentPosition((position)=>{setLocationError('');onUserLocation({lat:position.coords.latitude,lng:position.coords.longitude})},()=>setLocationError('Não foi possível acessar sua localização. Digite uma cidade na busca.'),{enableHighAccuracy:false,timeout:8000})}
  return <div className="map-panel"><div className="radius-control"><label htmlFor="radius">Distância máxima: {radiusKm} km</label><input id="radius" aria-label="Distância máxima da busca" type="range" min="0" max="4" step="1" value={[5,10,25,50,100].indexOf(radiusKm)} onInput={(e)=>setRadiusKm([5,10,25,50,100][Number(e.currentTarget.value)])}/><small>{userLocation?`Mostrando somente resultados em até ${radiusKm} km da sua localização.`:'Escolha a distância e use sua localização para buscar na região.'}</small><button className="map-locate-button" type="button" onClick={locate}><Crosshair size={15}/> Buscar perto de mim</button>{locationError&&<small className="map-location-error">{locationError}</small>}</div>
    <MapContainer center={center} zoom={points.length?10:4} zoomControl={false} scrollWheelZoom aria-label="Mapa de referências municipais dos resultados"><ZoomControl position="topright"/><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Fit points={points} active={active} userLocation={userLocation}/>{circleCenter&&<Circle center={[circleCenter.lat,circleCenter.lng]} radius={radiusKm*1000} pathOptions={{color:'var(--primary)',fillColor:'var(--primary-soft)',fillOpacity:.15}}/>}{userLocation&&<CircleMarker center={[userLocation.lat,userLocation.lng]} radius={7} pathOptions={{color:'var(--moss)',fillColor:'var(--moss-soft)',fillOpacity:1,weight:3}}><Popup>Sua localização aproximada</Popup></CircleMarker>}{groups.map((group)=>{const first=group.items?.[0];const isActive=group.items?.some((item)=>item.id===active);return <CircleMarker key={`${group.lat}:${group.lng}`} center={[group.lat,group.lng]} radius={isActive?14:Math.min(15,8+Math.log2(group.records+1)*1.5)} pathOptions={{color:'var(--amber)',fillColor:'var(--amber-soft)',fillOpacity:1,weight:3}} eventHandlers={first?{click:()=>onActive(first.id),keypress:()=>onActive(first.id)}:{}}><Popup><strong>{group.records} {group.records===1?'registro':'registros'} em {group.city}, {group.state}</strong><small>{group.institutions.length} {group.institutions.length===1?'instituição encontrada':'instituições encontradas'}</small>{group.institutions.map((institution)=><span className="map-popup-item" key={institution.id}>{institution.acronym||institution.name} · {institution.records} {institution.records===1?'curso':'cursos/registros'}</span>)}<small>Referência municipal, não endereço de campus.</small></Popup></CircleMarker>})}</MapContainer>
    {selected&&<div className="map-result-strip"><strong>{selected.course.name}</strong><span>{selected.institution.name}</span><small>{selected.location.city?`${selected.location.city}, ${selected.location.state}`:'Abrangência nacional'} · referência municipal</small></div>}
    <div className="map-notice"><strong>{mapLoading?'Atualizando o mapa…':'Cobertura do mapa:'}</strong> {coverage?`${coverage.represented.toLocaleString('pt-BR')} de ${coverage.total.toLocaleString('pt-BR')} registros considerados. `:'Sem cidade, estado ou curso, o mapa acompanha a página atual. '}{mapNotice||'Os pontos são referências municipais; o Censo 2024 não informa o endereço do campus.'}</div>
  </div>
}
