import { Circle,CircleMarker,MapContainer,Popup,TileLayer,useMap,ZoomControl } from 'react-leaflet';
import { Crosshair } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';

function Fit({items,active,userLocation}){const map=useMap();useEffect(()=>{if(userLocation){map.flyTo([userLocation.lat,userLocation.lng],11,{duration:.5});return}const item=items.find((x)=>x.id===active)||items[0];if(item?.location?.lat&&item?.location?.lng)map.flyTo([item.location.lat,item.location.lng],active?12:10,{duration:.5});},[items,active,userLocation,map]);return null}

export function ResultsMap({items,active,onActive,radiusKm,setRadiusKm,userLocation,onUserLocation}){
  const [locationError,setLocationError]=useState('');
  const located=items.filter((item)=>item.location?.lat&&item.location?.lng);
  const groups=useMemo(()=>{const map=new Map();for(const item of located){const key=`${item.location.lat.toFixed(3)}:${item.location.lng.toFixed(3)}`;if(!map.has(key))map.set(key,[]);map.get(key).push(item)}return [...map.values()]},[located]);
  const selected=items.find((item)=>item.id===active)||items[0];const center=userLocation?[userLocation.lat,userLocation.lng]:located[0]?[located[0].location.lat,located[0].location.lng]:[-14.235,-51.925];const circleCenter=userLocation||located[0]?.location;
  function locate(){if(!navigator.geolocation){setLocationError('Seu navegador não oferece localização. Digite uma cidade na busca.');return}navigator.geolocation.getCurrentPosition((position)=>{setLocationError('');onUserLocation({lat:position.coords.latitude,lng:position.coords.longitude})},()=>setLocationError('Não foi possível acessar sua localização. Digite uma cidade na busca.'),{enableHighAccuracy:false,timeout:8000})}
  return <div className="map-panel"><div className="radius-control"><label htmlFor="radius">Raio visual: {radiusKm} km</label><input id="radius" type="range" min="0" max="4" step="1" value={[5,10,25,50,100].indexOf(radiusKm)} onChange={(e)=>setRadiusKm([5,10,25,50,100][e.target.value])}/><small>{userLocation?'Círculo centralizado na sua localização.':'O círculo usa a referência do município, não um campus.'}</small><button className="map-locate-button" type="button" onClick={locate}><Crosshair size={15}/> Usar minha localização</button>{locationError&&<small className="map-location-error">{locationError}</small>}</div>
    <MapContainer center={center} zoom={located.length?10:4} zoomControl={false} scrollWheelZoom aria-label="Mapa de referências municipais dos resultados"><ZoomControl position="topright"/><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Fit items={located} active={active} userLocation={userLocation}/>{circleCenter&&<Circle center={[circleCenter.lat,circleCenter.lng]} radius={radiusKm*1000} pathOptions={{color:'var(--primary)',fillColor:'var(--primary-soft)',fillOpacity:.15}}/>}{userLocation&&<CircleMarker center={[userLocation.lat,userLocation.lng]} radius={7} pathOptions={{color:'var(--moss)',fillColor:'var(--moss-soft)',fillOpacity:1,weight:3}}><Popup>Sua localização aproximada</Popup></CircleMarker>}{groups.map((group)=>{const first=group[0];const isActive=group.some((item)=>item.id===active);return <CircleMarker key={`${first.location.lat}:${first.location.lng}`} center={[first.location.lat,first.location.lng]} radius={isActive?14:Math.min(13,8+group.length)} pathOptions={{color:'var(--amber)',fillColor:'var(--amber-soft)',fillOpacity:1,weight:3}} eventHandlers={{click:()=>onActive(first.id),keypress:()=>onActive(first.id)}}><Popup><strong>{group.length} {group.length===1?'registro':'registros'} em {first.location.city}</strong>{group.slice(0,5).map((item)=><span className="map-popup-item" key={item.id}>{item.course.name} · {item.institution.acronym||item.institution.name}</span>)}<small>Referência municipal, não campus.</small></Popup></CircleMarker>})}</MapContainer>
    {selected&&<div className="map-result-strip"><strong>{selected.course.name}</strong><span>{selected.institution.name}</span><small>{selected.location.city?`${selected.location.city}, ${selected.location.state}`:'Abrangência nacional'} · referência municipal</small></div>}
    <div className="map-notice"><strong>Importante:</strong> os pontos representam referências aproximadas do município. O Censo não informa o endereço do campus destes registros.</div>
  </div>
}
