import { createHash,randomBytes,scrypt as scryptCallback,timingSafeEqual } from 'node:crypto';import { promisify } from 'node:util';import * as db from '../repositories/authRepository.js';import * as demo from '../repositories/demoAuthRepository.js';import { env } from '../config/env.js';import { AppError } from '../errors/AppError.js';
const scrypt=promisify(scryptCallback);const repo=()=>env.DATA_MODE==='demo'?demo:db;const tokenHash=(token)=>createHash('sha256').update(token).digest('hex');
async function hashPassword(password){const salt=randomBytes(16).toString('hex');const derived=await scrypt(password,salt,64);return `${salt}:${Buffer.from(derived).toString('hex')}`}
async function verifyPassword(password,stored){const [salt,hex]=stored.split(':');const derived=Buffer.from(await scrypt(password,salt,64));const expected=Buffer.from(hex,'hex');return derived.length===expected.length&&timingSafeEqual(derived,expected)}
async function issue(user){const token=randomBytes(32).toString('base64url');const expiresAt=new Date(Date.now()+30*24*60*60*1000);await repo().createSession(user.id,tokenHash(token),expiresAt);return {token,expiresAt,user:{id:user.id,name:user.name,email:user.email,role:user.role}}}
export async function register(data){if(await repo().findUserByEmail(data.email))throw new AppError('EMAIL_EM_USO','Este e-mail já possui uma conta.',{status:409,hint:'Entre com sua senha ou use outro e-mail.'});try{const user=await repo().createUser({name:data.name,email:data.email,passwordHash:await hashPassword(data.password)});return issue(user)}catch(error){if(error.code==='23505')throw new AppError('EMAIL_EM_USO','Este e-mail já possui uma conta.',{status:409,hint:'Entre com sua senha ou use outro e-mail.'});throw error}}
export async function login(data){const user=await repo().findUserByEmail(data.email);if(!user||!await verifyPassword(data.password,user.password_hash))throw new AppError('CREDENCIAIS_INVALIDAS','E-mail ou senha incorretos.',{status:401,hint:'Confira os dados e tente novamente.'});return issue(user)}
export async function authenticate(token){if(!token)return null;return repo().findUserBySession(tokenHash(token))}
export async function logout(token){if(token)await repo().deleteSession(tokenHash(token))}
export async function getPlan(user){return repo().listPlan(user.id)}
export async function addPlan(user,data){const item=await repo().addPlanItem(user.id,data.recordId,data.notes);if(!item)throw new AppError('REGISTRO_NAO_ENCONTRADO','Registro de curso não encontrado.',{status:404,hint:'Volte para a busca e escolha outro resultado.'});return item}
export async function removePlan(user,id){if(!await repo().removePlanItem(user.id,id))throw new AppError('ITEM_NAO_ENCONTRADO','Item do plano não encontrado.',{status:404,hint:'Atualize a página e tente novamente.'})}
export async function reviewQueue(user){if(!['reviewer','admin'].includes(user.role))throw new AppError('ACESSO_NEGADO','Seu perfil não pode acessar a fila de revisão.',{status:403});return repo().listCorrections()}
export async function updateReview(user,id,status){if(!['reviewer','admin'].includes(user.role))throw new AppError('ACESSO_NEGADO','Seu perfil não pode revisar correções.',{status:403});const result=await repo().updateCorrection(id,status,user.id);if(!result)throw new AppError('CORRECAO_NAO_ENCONTRADA','Correção não encontrada.',{status:404});return result}
