import { useState } from 'react';
import { Link,useLocation,useNavigate } from 'react-router-dom';
import { api } from '../services/api.js';
import { saveSession } from '../lib/auth.js';
import { Seo } from '../components/Seo.jsx';
import { Breadcrumbs } from '../components/Breadcrumbs.jsx';
import { safeInternalPath } from '../lib/navigation.js';

export function AuthPage(){const [mode,setMode]=useState('login');const [form,setForm]=useState({name:'',email:'',password:''});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const navigate=useNavigate();const location=useLocation();async function submit(e){e.preventDefault();setBusy(true);setError('');try{const result=await api(`/auth/${mode}`,{method:'POST',body:JSON.stringify(form)});saveSession(result.data);const requested=new URLSearchParams(location.search).get('voltar');navigate(safeInternalPath(requested,'/meu-plano'))}catch(err){setError(err.payload?.error?.message||err.message)}finally{setBusy(false)}}return <><Seo title="Entrar | Faculdade Perto" description="Entre ou crie sua conta para salvar cursos no Meu Plano." path="/entrar" noindex/><header className="page-header"><Breadcrumbs items={[{label:'Entrar'}]}/><h1>{mode==='login'?'Continue seu plano.':'Crie seu espaço.'}</h1><p>Salve cursos para rever depois. Seus dados não mudam as informações públicas do catálogo.</p></header><section className="section compact-section"><form className="form-card auth-card" onSubmit={submit}>{error&&<div className="form-error" role="alert">{error}</div>}{mode==='register'&&<label className="form-field"><span>Nome</span><input autoComplete="name" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} required minLength={2}/></label>}<label className="form-field"><span>E-mail</span><input type="email" autoComplete="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} required/></label><label className="form-field"><span>Senha</span><input type="password" autoComplete={mode==='login'?'current-password':'new-password'} value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})} required minLength={8}/></label><button className="primary-button" disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar':'Criar conta'}</button><button type="button" className="text-button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Ainda não tenho conta':'Já tenho uma conta'}</button><small>Ao continuar, você concorda com os <Link to="/termos">Termos de uso</Link> e declara ter lido a <Link to="/privacidade">Política de Privacidade</Link>.</small></form></section></>}
