import { useQueries } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { X } from 'lucide-react';
import { useState } from 'react';
import { api } from '../services/api.js';
import { Seo } from '../components/Seo.jsx';
import { Breadcrumbs } from '../components/Breadcrumbs.jsx';
export const readCompare=()=>{try{return JSON.parse(localStorage.getItem('fp_compare')||'[]').slice(0,4)}catch{return []}};
export function writeCompare(ids){localStorage.setItem('fp_compare',JSON.stringify([...new Set(ids)].slice(0,4)));window.dispatchEvent(new Event('faculdade-compare'))}
export function ComparePage(){const [ids,setIds]=useState(readCompare);const queries=useQueries({queries:ids.map((id)=>({queryKey:['record',String(id)],queryFn:()=>api(`/catalog-records/${id}`)}))});const records=queries.filter((q)=>q.data).map((q)=>q.data.data);function remove(id){const next=ids.filter((x)=>String(x)!==String(id));writeCompare(next);setIds(next)}return <><Seo title="Comparar cursos | Faculdade Perto" description="Compare até quatro registros do Censo 2024 sem ocultar os limites dos dados." path="/comparar" noindex/><header className="page-header"><Breadcrumbs items={[{label:'Comparar'}]}/><h1>Compare sem perder o contexto.</h1><p>Até quatro registros lado a lado. “Não confirmado” continua visível e nenhum registro agregado vira oferta ativa.</p></header><section className="section compact-section">{ids.length===0?<div className="empty-state"><h2>Nenhum curso na comparação.</h2><p>Abra registros na busca e adicione os que quer avaliar.</p><Link className="primary-button" to="/buscar">Buscar cursos</Link></div>:queries.some((q)=>q.isLoading)?<div className="loading-state">Montando a comparação…</div>:queries.every((q)=>q.isError)?<div className="error-state"><h2>Não foi possível montar a comparação.</h2><p>Atualize a página ou escolha outros registros.</p></div>:<div className="compare-wrap">{queries.some((q)=>q.isError)&&<p className="notice">Um dos registros não pôde ser carregado e foi omitido.</p>}<table className="compare-table"><thead><tr><th>Campo</th>{records.map((r)=><th key={r.id}><button className="icon-button" onClick={()=>remove(r.id)} aria-label={`Remover ${r.course.name}`}><X size={17}/></button><Link to={`/ofertas/${r.id}`}>{r.course.name}</Link></th>)}</tr></thead><tbody><tr><th>Instituição</th>{records.map((r)=><td key={r.id}>{r.institution.name}</td>)}</tr><tr><th>Cidade</th>{records.map((r)=><td key={r.id}>{r.location.city}, {r.location.state}</td>)}</tr><tr><th>Grau</th>{records.map((r)=><td key={r.id}>{r.degree.value||'Não confirmado'}</td>)}</tr><tr><th>Modalidade</th>{records.map((r)=><td key={r.id}>{r.modality.value||'Não confirmado'}</td>)}</tr><tr><th>Vagas em 2024</th>{records.map((r)=><td key={r.id}>{r.censusSeats.value??'Não confirmado'}</td>)}</tr><tr><th>Mensalidade</th>{records.map((r)=><td key={r.id}>Não confirmado</td>)}</tr><tr><th>Nota de corte</th>{records.map((r)=><td key={r.id}>Não confirmado</td>)}</tr></tbody></table><p className="notice">Todos os itens são registros agregados do Censo 2024; não confirmam campus nem oferta atual.</p></div>}</section></>}
