import { ArrowRight,Database,MapPinned,ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Seo } from '../components/Seo.jsx';
import { SearchBar } from '../components/SearchBar.jsx';
import { FaqList } from '../components/FaqList.jsx';
import { faqs } from '../data/faqs.js';

export function HomePage(){const faqLd={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map((f)=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))};return <>
  <Seo title="Faculdade Perto — encontre cursos e faculdades com fonte" description="Busque faculdades e cursos por cidade. Veja a fonte, o ano e o status de cada dado — sem mensalidades ou notas inventadas." jsonLd={faqLd}/>
  <section className="hero"><p className="eyebrow"><ShieldCheck size={16}/> Informação educacional sem adivinhação</p><h1>Que curso você quer, e onde você mora?</h1><p className="hero-copy">Explore cursos e instituições do Brasil com uma diferença simples: cada informação diz de onde veio, quando foi atualizada e o que ainda não foi confirmado.</p><SearchBar large/></section>
  <section className="trust-strip" aria-label="Compromissos do site"><div className="trust-item"><Database/><div><strong>Fonte em cada dado</strong><p>Censo INEP, ano e importação sempre visíveis.</p></div></div><div className="trust-item"><ShieldCheck/><div><strong>Sem estimativas escondidas</strong><p>O que falta aparece como não confirmado.</p></div></div><div className="trust-item"><MapPinned/><div><strong>Localização com contexto</strong><p>Município de referência não é apresentado como campus.</p></div></div></section>
  <section className="section"><div className="section-heading"><div><p className="eyebrow">Como funciona</p><h2>Menos promessa. Mais contexto.</h2></div><p>Uma busca educacional precisa ajudar sem apagar as limitações das fontes. Por isso, o status do dado faz parte da experiência — não fica escondido no rodapé.</p></div><div className="steps"><article className="step"><span className="step-number">01</span><h3>Procure</h3><p>Digite o curso, a instituição e a cidade que você quer explorar.</p></article><article className="step"><span className="step-number">02</span><h3>Compare o contexto</h3><p>Separe grau, modalidade, categoria administrativa e gratuidade.</p></article><article className="step"><span className="step-number">03</span><h3>Confira a fonte</h3><p>Abra o selo ao lado do valor para ver origem, ano e limite do dado.</p></article></div></section>
  <section className="section"><div className="section-heading"><div><p className="eyebrow">Comece por uma cidade</p><h2>Descubra por perto</h2></div><Link className="secondary-button" to="/buscar">Ver busca completa <ArrowRight size={17}/></Link></div><div className="cities"><Link className="city-link" to="/br/sp/campinas"><strong>Campinas</strong><span>São Paulo</span></Link><Link className="city-link" to="/buscar?city=São+Paulo"><strong>São Paulo</strong><span>São Paulo</span></Link><Link className="city-link" to="/buscar?city=Sorocaba"><strong>Sorocaba</strong><span>São Paulo</span></Link><Link className="city-link" to="/buscar"><strong>Todo o Brasil</strong><span>Busque por cidade ou estado</span></Link></div></section>
  <section className="section"><div className="section-heading"><div><p className="eyebrow">Dúvidas reais</p><h2>Antes de escolher</h2></div><p>Entenda como ler gratuidade, mensalidade, notas históricas e tipos de graduação.</p></div><FaqList items={faqs}/></section>
  </>}
