import { ArrowRight,BookOpenCheck,Compass,Database,MapPin,MapPinned,Scale,Search,ShieldCheck,Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Seo } from '../components/Seo.jsx';
import { SearchBar } from '../components/SearchBar.jsx';
import { FaqList } from '../components/FaqList.jsx';
import { faqs } from '../data/faqs.js';

export function HomePage(){const faqLd={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map((f)=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))};return <>
  <Seo title="Faculdade Perto — encontre cursos e faculdades com fonte" description="Busque faculdades e cursos por cidade. Veja a fonte, o ano e o status de cada dado — sem mensalidades ou notas inventadas." jsonLd={faqLd}/>
  <section className="hero"><div className="hero-grid"><div className="hero-content"><p className="eyebrow"><Sparkles size={16}/> Sua busca começa com dados claros</p><h1>Encontre seu caminho no <span>ensino superior.</span></h1><p className="hero-copy">Pesquise cursos e instituições em todo o Brasil. Compare modalidade, grau, gratuidade, turno e localização com a fonte de cada informação sempre visível.</p><SearchBar large/><p className="hero-assurance"><ShieldCheck size={16}/> Dados oficiais do Censo Superior 2024, sem posições patrocinadas.</p></div><aside className="hero-preview" aria-label="Resumo da base nacional"><div className="preview-top"><span><MapPinned size={18}/> Base nacional</span><strong>Atualizada</strong></div><div className="preview-feature"><span className="preview-icon"><BookOpenCheck/></span><div><small>Catálogo pesquisável</small><strong>720.349 registros</strong><span>de cursos no Censo 2024</span></div></div><div className="preview-stats"><div><strong>2.561</strong><span>instituições</span></div><div><strong>353</strong><span>cursos</span></div><div><strong>27</strong><span>UFs</span></div></div><div className="preview-place"><MapPin size={17}/><div><strong>Do seu estado ao Brasil inteiro</strong><span>Filtros rápidos e mapa com contexto</span></div></div></aside></div></section>
  <section className="trust-strip" aria-label="Compromissos do site"><div className="trust-item"><Database/><div><strong>Fonte em cada dado</strong><p>Censo INEP, ano e importação sempre visíveis.</p></div></div><div className="trust-item"><ShieldCheck/><div><strong>Sem estimativas escondidas</strong><p>O que falta aparece como não confirmado.</p></div></div><div className="trust-item"><MapPinned/><div><strong>Localização com contexto</strong><p>Município de referência não é apresentado como campus.</p></div></div></section>
  <section className="section decision-entry"><div className="section-heading"><div><p className="eyebrow"><Compass size={16}/> Bússola da Escolha</p><h2>Comece do ponto em que você está.</h2></div><p>Suas prioridades viram caminhos explicáveis. Nada de ranking escondido ou instituição favorecida.</p></div><div className="decision-grid"><Link to="/bussola?intent=course" className="decision-card"><Search/><strong>Já sei o curso</strong><span>Encontre onde estudar e compare os registros.</span></Link><Link to="/bussola?intent=explore" className="decision-card featured"><Compass/><strong>Ainda estou descobrindo</strong><span>Explore áreas e preferências sem um teste vocacional enganoso.</span></Link><Link to="/bussola?intent=nearby" className="decision-card"><MapPinned/><strong>Quero estudar perto</strong><span>Veja como distância, modalidade e turno mudam suas opções.</span></Link><Link to="/bussola?intent=scenarios" className="decision-card"><Scale/><strong>Quero comparar cenários</strong><span>Entenda o que muda ao aceitar EAD ou outra cidade.</span></Link></div></section>
  <section className="section"><div className="section-heading"><div><p className="eyebrow">Como funciona</p><h2>Menos promessa. Mais contexto.</h2></div><p>Uma busca educacional precisa ajudar sem apagar as limitações das fontes. Por isso, o status do dado faz parte da experiência — não fica escondido no rodapé.</p></div><div className="steps"><article className="step"><span className="step-number">01</span><h3>Procure</h3><p>Digite o curso, a instituição e a cidade que você quer explorar.</p></article><article className="step"><span className="step-number">02</span><h3>Compare o contexto</h3><p>Separe grau, modalidade, categoria administrativa e gratuidade.</p></article><article className="step"><span className="step-number">03</span><h3>Confira a fonte</h3><p>Abra o selo ao lado do valor para ver origem, ano e limite do dado.</p></article></div></section>
  <section className="section"><div className="section-heading"><div><p className="eyebrow">Comece por uma cidade</p><h2>Descubra por perto</h2></div><Link className="secondary-button" to="/buscar">Ver busca completa <ArrowRight size={17}/></Link></div><div className="cities"><Link className="city-link" to="/br/sp/campinas"><strong>Campinas</strong><span>São Paulo</span></Link><Link className="city-link" to="/buscar?city=São+Paulo"><strong>São Paulo</strong><span>São Paulo</span></Link><Link className="city-link" to="/buscar?city=Sorocaba"><strong>Sorocaba</strong><span>São Paulo</span></Link><Link className="city-link" to="/buscar"><strong>Todo o Brasil</strong><span>Busque por cidade ou estado</span></Link></div></section>
  <section className="section"><div className="section-heading"><div><p className="eyebrow">Dúvidas reais</p><h2>Antes de escolher</h2></div><p>Entenda como ler gratuidade, mensalidade, notas históricas e tipos de graduação.</p></div><FaqList items={faqs}/></section>
  </>}
