import { useQuery } from '@tanstack/react-query';
import { Building2,MapPin,ShieldAlert } from 'lucide-react';
import { Link,useParams,useSearchParams } from 'react-router-dom';
import { Breadcrumbs } from '../components/Breadcrumbs.jsx';
import { DataBadge } from '../components/DataBadge.jsx';
import { Seo } from '../components/Seo.jsx';
import { api,queryString } from '../services/api.js';

export function InstitutionPage(){
  const {slug}=useParams();const [params,setParams]=useSearchParams();const page=Math.max(1,Number(params.get('page')||1));
  const query=useQuery({queryKey:['institution',slug,page],queryFn:()=>api(`/institutions/${slug}?${queryString({page,limit:30})}`)});
  if(query.isLoading)return <div className="page-header"><div className="skeleton"/></div>;
  if(query.isError)return <><Seo title="Instituição não encontrada | Faculdade Perto" description="A instituição solicitada não foi encontrada." path={`/instituicoes/${slug}`} noindex/><div className="page-header error-state"><h1>Instituição não encontrada</h1><p>{query.error.message} {query.error.payload?.error?.hint}</p><Link className="primary-button" to="/buscar">Voltar para a busca</Link></div></>;
  const item=query.data.data;const hq=item.headquarters.value;const pagination=item.recordsPagination;const title=`${item.name.value} — cursos e dados | Faculdade Perto`;
  const ld={'@context':'https://schema.org','@type':'EducationalOrganization',name:item.name.value,alternateName:item.acronym.value,address:hq?.address?{'@type':'PostalAddress',addressLocality:hq.city,addressRegion:hq.state,streetAddress:`${hq.address.street||''}, ${hq.address.number||''}`}:{'@type':'PostalAddress',addressLocality:hq?.city,addressRegion:hq?.state}};
  function go(nextPage){const next=new URLSearchParams(params);if(nextPage>1)next.set('page',String(nextPage));else next.delete('page');setParams(next);window.scrollTo({top:0,behavior:'smooth'})}
  return <><Seo title={title} description={`Veja cursos registrados para ${item.name.value}, categoria administrativa, município da sede e fonte dos dados.`} path={`/instituicoes/${slug}`} jsonLd={ld}/><header className="page-header"><Breadcrumbs items={[{label:hq.state,to:`/buscar?state=${hq.state}`},{label:hq.city,to:`/br/${hq.state.toLowerCase()}/${hq.citySlug}`},{label:item.name.value}]}/><p className="eyebrow"><Building2 size={16}/>{item.academicOrganization.value||'Organização não confirmada'}</p><h1>{item.name.value}</h1><p>{item.acronym.value} · Código INEP {item.inepCode}</p></header><div className="detail-grid"><section className="detail-main"><div className="notice"><ShieldAlert size={18}/> O endereço abaixo é da sede administrativa ou reitoria. O Censo 2024 não o identifica como campus.</div><article className="info-card"><h2>Sobre a instituição</h2><dl className="fact-list"><div><dt>Rede</dt><dd>{item.network.value==='publica'?'Pública':'Privada'}</dd><DataBadge field={item.network}/></div><div><dt>Categoria</dt><dd>{item.administrativeCategory.value||'Não confirmado'}</dd><DataBadge field={item.administrativeCategory}/></div><div><dt>Mantenedora</dt><dd>{item.maintainer.value||'Não confirmado'}</dd><DataBadge field={item.maintainer}/></div><div><dt>Sede</dt><dd><MapPin size={15}/> {hq.city}, {hq.state}</dd><DataBadge field={item.headquarters}/></div></dl></article><article className="info-card"><h2>{pagination.total.toLocaleString('pt-BR')} registros de cursos no Censo 2024</h2><div className="course-list">{item.records.map((record)=><Link className="course-row" to={`/ofertas/${record.id}`} key={record.id}><div><strong>{record.canonical_name}</strong><span>{record.degree} · {record.modality} · código {record.inep_course_code}</span></div><strong>{record.census_seats!==null?`${Number(record.census_seats)} vagas no Censo`:'Vagas não confirmadas'}</strong></Link>)}</div>{pagination.totalPages>1&&<nav className="pagination" aria-label="Paginação dos cursos"><button className="secondary-button" disabled={page<=1} onClick={()=>go(page-1)}>Anterior</button><span>Página {page} de {pagination.totalPages}</span><button className="secondary-button" disabled={page>=pagination.totalPages} onClick={()=>go(page+1)}>Próxima</button></nav>}</article></section><aside className="detail-aside"><article className="info-card"><h2>O que ainda falta</h2><p>Campus, polo, situação regulatória atual, mensalidade e processos seletivos precisam de fontes complementares.</p><DataBadge field={item.campusNotice}/></article><Link className="secondary-button" to={`/corrigir?entityType=institution&entityId=${item.id}`}>Encontrou um erro?</Link></aside></div></>;
}
