import { useQuery,useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Bookmark,Trash2 } from 'lucide-react';
import { api } from '../services/api.js';
import { getToken } from '../lib/auth.js';
import { Seo } from '../components/Seo.jsx';
import { Breadcrumbs } from '../components/Breadcrumbs.jsx';

export function PlanPage(){const client=useQueryClient();const logged=Boolean(getToken());const query=useQuery({queryKey:['plan'],queryFn:()=>api('/me/plan'),enabled:logged});async function remove(id){await api(`/me/plan/${id}`,{method:'DELETE'});client.invalidateQueries({queryKey:['plan']})}return <><Seo title="Meu Plano | Faculdade Perto" description="Cursos salvos para organizar sua pesquisa." path="/meu-plano" noindex/><header className="page-header"><Breadcrumbs items={[{label:'Meu Plano'}]}/><p className="eyebrow"><Bookmark size={16}/> Seu espaço</p><h1>Meu Plano</h1><p>Reúna opções para voltar com calma. Salvar um registro não confirma oferta ativa, campus, preço ou ingresso.</p></header><section className="section compact-section">{!logged?<div className="empty-state"><h2>Entre para guardar seu plano.</h2><p>Sua lista fica ligada à sua conta.</p><Link className="primary-button" to="/entrar?voltar=/meu-plano">Entrar ou criar conta</Link></div>:query.isLoading?<div className="loading-state">Carregando seu plano…</div>:query.isError?<div className="error-state"><h2>Não foi possível abrir o plano.</h2><p>{query.error.message}</p><Link className="secondary-button" to="/entrar?voltar=/meu-plano">Entrar novamente</Link></div>:query.data.data.length===0?<div className="empty-state"><h2>Seu plano ainda está vazio.</h2><p>Abra um curso e escolha “Salvar no Meu Plano”.</p><Link className="primary-button" to="/buscar">Buscar cursos</Link></div>:<div className="saved-grid">{query.data.data.map((item)=><article className="saved-card" key={item.plan_item_id}><div><span>{item.degree||'Grau não confirmado'} · {item.modality||'Modalidade não confirmada'}</span><h2><Link to={`/ofertas/${item.id}`}>{item.canonical_name||item.original_name}</Link></h2><p>{item.institution_name}</p><small>{item.municipality_name}, {item.state_abbreviation}</small>{item.notes&&<p className="plan-note">“{item.notes}”</p>}</div><button className="icon-button" onClick={()=>remove(item.plan_item_id)} aria-label={`Remover ${item.canonical_name} do plano`}><Trash2 size={18}/></button></article>)}</div>}</section></>}
