import { pool,withTransaction } from '../database/pool.js';
export async function findUserByEmail(email){return (await pool.query('SELECT * FROM users WHERE email=$1',[email])).rows[0]||null}
export async function createUser({name,email,passwordHash,role}){return (await pool.query(`INSERT INTO users(name,email,password_hash,role) VALUES ($1,$2,$3,$4) RETURNING id,name,email,role,created_at`,[name,email,passwordHash,role||'user'])).rows[0]}
export async function createSession(userId,tokenHash,expiresAt){await pool.query('DELETE FROM user_sessions WHERE expires_at<now()');await pool.query(`INSERT INTO user_sessions(user_id,token_hash,expires_at) VALUES ($1,$2,$3)`,[userId,tokenHash,expiresAt])}
export async function findUserBySession(tokenHash){return (await pool.query(`SELECT u.id,u.name,u.email,u.role FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now()`,[tokenHash])).rows[0]||null}
export async function deleteSession(tokenHash){return (await pool.query('DELETE FROM user_sessions WHERE token_hash=$1',[tokenHash])).rowCount>0}
export async function listPlan(userId){return (await pool.query(`SELECT pi.id plan_item_id,pi.notes,pi.created_at,ccr.id,ccr.original_name,ccr.degree,ccr.modality,c.canonical_name,i.name institution_name,i.slug institution_slug,m.name municipality_name,s.abbreviation state_abbreviation FROM plan_items pi JOIN course_catalog_records ccr ON ccr.id=pi.catalog_record_id JOIN courses c ON c.id=ccr.course_id JOIN institutions i ON i.id=ccr.institution_id LEFT JOIN municipalities m ON m.id=ccr.municipality_id LEFT JOIN states s ON s.id=m.state_id WHERE pi.user_id=$1 ORDER BY pi.created_at DESC`,[userId])).rows}
export async function addPlanItem(userId,recordId,notes){return (await pool.query(`INSERT INTO plan_items(user_id,catalog_record_id,notes) VALUES ($1,$2,$3) ON CONFLICT(user_id,catalog_record_id) DO UPDATE SET notes=EXCLUDED.notes RETURNING id,created_at`,[userId,recordId,notes||null])).rows[0]}
export async function removePlanItem(userId,id){return (await pool.query('DELETE FROM plan_items WHERE user_id=$1 AND id=$2 RETURNING id',[userId,id])).rowCount>0}
export async function listCorrections(){return (await pool.query('SELECT * FROM corrections ORDER BY created_at DESC LIMIT 200')).rows}
export async function updateCorrection(id,status,userId){return withTransaction(async(db)=>{const result=(await db.query('UPDATE corrections SET status=$1 WHERE id=$2 RETURNING *',[status,id])).rows[0];if(result)await db.query(`INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata) VALUES ($1,'correction.status_updated','correction',$2,$3)`,[userId,id,{status}]);return result||null})}
