const importedAt='2026-08-21T00:00:00.000Z';
const source_name='Censo da Educação Superior 2024';
const source_url='https://download.inep.gov.br/microdados/microdados_censo_da_educacao_superior_2024.zip';
const institutions=[
  {id:1,inep_code:'54',name:'UNIVERSIDADE ESTADUAL DE CAMPINAS',acronym:'UNICAMP',slug:'universidade-estadual-de-campinas-54',education_network:'publica',administrative_category:'Pública Estadual',academic_organization:'Universidade',municipality_name:'Campinas',municipality_slug:'campinas',state_name:'São Paulo',state_abbreviation:'SP',maintainer_name:'UNIVERSIDADE ESTADUAL DE CAMPINAS',headquarters_address:{street:'Cidade Universitária',number:'S/N',neighborhood:'Barão Geraldo',postalCode:'13083970'},source_name,source_url,imported_at:importedAt,reference_period:'2024'},
  {id:2,inep_code:'19',name:'PONTIFÍCIA UNIVERSIDADE CATÓLICA DE CAMPINAS',acronym:'PUC-CAMPINAS',slug:'pontificia-universidade-catolica-de-campinas-19',education_network:'privada',administrative_category:'Privada sem fins lucrativos',academic_organization:'Universidade',municipality_name:'Campinas',municipality_slug:'campinas',state_name:'São Paulo',state_abbreviation:'SP',maintainer_name:'SOCIEDADE CAMPINEIRA DE EDUCACAO E INSTRUCAO',headquarters_address:{street:'Rua Professor Doutor Euryclides de Jesus Zerbini',number:'1516',neighborhood:'Parque Rural Fazenda Santa Cândida',postalCode:'13087571'},source_name,source_url,imported_at:importedAt,reference_period:'2024'},
  {id:3,inep_code:'322',name:'UNIVERSIDADE PAULISTA',acronym:'UNIP',slug:'universidade-paulista-322',education_network:'privada',administrative_category:'Privada com fins lucrativos',academic_organization:'Universidade',municipality_name:'São Paulo',municipality_slug:'sao-paulo',state_name:'São Paulo',state_abbreviation:'SP',maintainer_name:'ASSUPERO ENSINO SUPERIOR LTDA.',headquarters_address:{street:'Avenida Torres de Oliveira',number:'330',neighborhood:'Jaguaré',postalCode:'05347020'},source_name,source_url,imported_at:importedAt,reference_period:'2024'},
  {id:4,inep_code:'22',name:'UNIVERSIDADE PRESBITERIANA MACKENZIE',acronym:'MACKENZIE',slug:'universidade-presbiteriana-mackenzie-22',education_network:'privada',administrative_category:'Privada sem fins lucrativos',academic_organization:'Universidade',municipality_name:'São Paulo',municipality_slug:'sao-paulo',state_name:'São Paulo',state_abbreviation:'SP',maintainer_name:'INSTITUTO PRESBITERIANO MACKENZIE',headquarters_address:{street:'Rua da Consolação',number:'896',neighborhood:'Consolação',postalCode:'01302907'},source_name,source_url,imported_at:importedAt,reference_period:'2024'}
];
const baseCourses=[
  [1,'2695','Medicina','0912M01','bacharelado',true,122,731],[1,'2700','Pedagogia','0113P01','licenciatura',true,51,221],
  [2,'1654','Administração','0413A01','bacharelado',false,854,1358],[2,'1642','Direito','0421D01','bacharelado',false,574,1910],[2,'1629','Medicina','0912M01','bacharelado',false,134,868],
  [3,'7299','Administração','0413A01','bacharelado',false,407,285],[3,'7300','Direito','0421D01','bacharelado',false,526,561],[3,'5001416','Medicina','0912M01','bacharelado',false,105,210],[3,'18694','Pedagogia','0113P01','licenciatura',false,240,107],
  [4,'108112','Administração','0413A01','bacharelado',false,162,283]
];
const courses=baseCourses.map(([institution_id,code,name,cine,degree,free,seats,enrolled],index)=>{const i=institutions.find((x)=>x.id===institution_id);const city='Campinas';return {id:index+1,inep_course_code:code,original_name:name,degree,modality:'presencial',free_indicator:free,census_year:2024,course_id:['Medicina','Pedagogia','Administração','Direito'].indexOf(name)+1,course_slug:`${name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll(' ','-')}-${cine.toLowerCase()}`,cine_code:cine,canonical_name:name,institution_id:i.id,institution_name:i.name,acronym:i.acronym,institution_slug:i.slug,education_network:i.education_network,administrative_category:i.administrative_category,municipality_name:city,municipality_slug:'campinas',state_abbreviation:'SP',lat:-22.9056,lng:-47.0608,location_note:`Referência aproximada do município de ${city}; não representa um campus.`,source_name,source_url,imported_at:importedAt,census_seats:seats,enrolled,total:baseCourses.length};});
const filter=(rows,{q,city,state,network,modality,degree}={})=>rows.filter((r)=>(!q||`${r.canonical_name||''} ${r.institution_name||r.name}`.toLowerCase().includes(q.toLowerCase()))&&(!city||(r.municipality_name||'').toLowerCase()===city.toLowerCase())&&(!state||(r.state_abbreviation||'').toLowerCase()===state.toLowerCase())&&(!network||(r.education_network||r.network)===network)&&(!modality||r.modality===modality)&&(!degree||r.degree===degree));
export async function listInstitutions(filters){const rows=filter(institutions,filters);return rows.map((x)=>({...x,total:rows.length})).slice((filters.page-1)*filters.limit,filters.page*filters.limit)}
export async function findInstitution(id){return institutions.find((x)=>x.slug===id||String(x.id)===String(id)||x.inep_code===String(id))||null}
export async function listInstitutionCourses(id,{page=1,limit=30}={}){const rows=courses.filter((x)=>x.institution_id===id);return rows.map((row)=>({...row,total:rows.length})).slice((page-1)*limit,page*limit)}
export async function listCourses(filters){const grouped=new Map();for(const row of filter(courses,filters)){if(!grouped.has(row.cine_code))grouped.set(row.cine_code,{id:row.course_id,cine_code:row.cine_code,canonical_name:row.canonical_name,slug:row.course_slug,cine_general_area_name:null,record_count:0,institutions:new Set()});const g=grouped.get(row.cine_code);g.record_count++;g.institutions.add(row.institution_id)}const result=[...grouped.values()].map((x)=>({...x,institution_count:x.institutions.size,total:grouped.size}));return result.slice((filters.page-1)*filters.limit,filters.page*filters.limit)}
export async function searchCatalog(filters){const rows=filter(courses,filters);return rows.map((x)=>({...x,total:rows.length})).slice((filters.page-1)*filters.limit,filters.page*filters.limit)}
export async function searchCatalogMap(filters){const rows=await searchCatalog({...filters,page:1,limit:5000});const groups=new Map();for(const row of rows){const key=`${row.municipality_slug}:${row.state_abbreviation}`;if(!groups.has(key))groups.set(key,{city:row.municipality_name,citySlug:row.municipality_slug,state:row.state_abbreviation,lat:row.lat,lng:row.lng,records:0,institutions:new Map()});const group=groups.get(key);group.records++;if(!group.institutions.has(String(row.institution_id)))group.institutions.set(String(row.institution_id),{id:row.institution_id,name:row.institution_name,acronym:row.acronym,slug:row.institution_slug,records:0});group.institutions.get(String(row.institution_id)).records++}return {groups:[...groups.values()].map((group)=>({...group,institutions:[...group.institutions.values()]})),total:rows.length,represented:rows.length,truncated:false}}
export async function findCatalogRecord(id){const row=courses.find((x)=>String(x.id)===String(id));return row?{...row,reference_period:'2024',statistics:{QT_VG_TOTAL:row.census_seats,QT_MAT:row.enrolled}}:null}
export async function nearbyCampuses(){return []}export async function listOfferings(){return []}export async function findOffering(){return null}export async function listCutoffs(){return []}
export async function sitemapCoreData(){return {institutions:institutions.map((x)=>({slug:x.slug,updated_at:importedAt})),municipalities:[{slug:'campinas',abbreviation:'SP'},{slug:'sao-paulo',abbreviation:'SP'}]}}
export async function sitemapRecordCount(){return courses.length}
export async function sitemapRecordsPage(page,limit){return courses.slice((page-1)*limit,page*limit).map((x)=>({id:x.id,imported_at:importedAt}))}
export async function sitemapData(){return {...await sitemapCoreData(),recordCount:await sitemapRecordCount()}}
